# TCL File Generated by Component Editor 14.0
# Wed Oct 01 16:53:38 PDT 2014
# DO NOT MODIFY


# 
# avst_data_to_packet "AvST Data to Packet" v1.0
#  2014.10.01.16:53:38
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module avst_data_to_packet
# 
set_module_property DESCRIPTION ""
set_module_property NAME avst_lfsr_packet_gen
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "AvST LFSR Packet Generator"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property GROUP {Memtest}

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avst_lfsr_packet_gen
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avst_lfsr_packet_gen.sv SYSTEM_VERILOG PATH avst_lfsr_packet_gen.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avst_lfsr_packet_gen
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avst_lfsr_packet_gen.sv SYSTEM_VERILOG PATH avst_lfsr_packet_gen.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL avst_lfsr_packet_gen
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avst_lfsr_packet_gen.sv SYSTEM_VERILOG PATH avst_lfsr_packet_gen.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point size
# 
add_interface size avalon_streaming end
set_interface_property size associatedClock clock
set_interface_property size associatedReset reset
set_interface_property size dataBitsPerSymbol 8
set_interface_property size errorDescriptor ""
set_interface_property size firstSymbolInHighOrderBits true
set_interface_property size maxChannel 0
set_interface_property size readyLatency 0
set_interface_property size ENABLED true
set_interface_property size EXPORT_OF ""
set_interface_property size PORT_NAME_MAP ""
set_interface_property size CMSIS_SVD_VARIABLES ""
set_interface_property size SVD_ADDRESS_GROUP ""

add_interface_port size asi_size_valid valid Input 1
add_interface_port size asi_size_data data Input 32


# 
# connection point data
# 
add_interface data avalon_streaming start
set_interface_property data associatedClock clock
set_interface_property data associatedReset reset
set_interface_property data dataBitsPerSymbol 8
set_interface_property data errorDescriptor ""
set_interface_property data firstSymbolInHighOrderBits true
set_interface_property data maxChannel 0
set_interface_property data readyLatency 0
set_interface_property data ENABLED true
set_interface_property data EXPORT_OF ""
set_interface_property data PORT_NAME_MAP ""
set_interface_property data CMSIS_SVD_VARIABLES ""
set_interface_property data SVD_ADDRESS_GROUP ""

add_interface_port data aso_data_valid valid Output 1
add_interface_port data aso_data_data data Output 128
add_interface_port data aso_data_ready ready Input 1
add_interface_port data aso_data_sop startofpacket Output 1
add_interface_port data aso_data_eop endofpacket Output 1
add_interface_port data aso_data_empty empty Output 4


# 
# connection point seed
# 
add_interface seed avalon_streaming end
set_interface_property seed associatedClock clock
set_interface_property seed associatedReset reset
set_interface_property seed dataBitsPerSymbol 8
set_interface_property seed errorDescriptor ""
set_interface_property seed firstSymbolInHighOrderBits true
set_interface_property seed maxChannel 0
set_interface_property seed readyLatency 0
set_interface_property seed ENABLED true
set_interface_property seed EXPORT_OF ""
set_interface_property seed PORT_NAME_MAP ""
set_interface_property seed CMSIS_SVD_VARIABLES ""
set_interface_property seed SVD_ADDRESS_GROUP ""

add_interface_port seed asi_seed_data data Input 128
add_interface_port seed asi_seed_valid valid Input 1


# 
# connection point status
# 
add_interface status avalon_streaming start
set_interface_property status associatedClock clock
set_interface_property status associatedReset reset
set_interface_property status dataBitsPerSymbol 4
set_interface_property status errorDescriptor ""
set_interface_property status firstSymbolInHighOrderBits true
set_interface_property status maxChannel 0
set_interface_property status readyLatency 0
set_interface_property status ENABLED true
set_interface_property status EXPORT_OF ""
set_interface_property status PORT_NAME_MAP ""
set_interface_property status CMSIS_SVD_VARIABLES ""
set_interface_property status SVD_ADDRESS_GROUP ""

add_interface_port status aso_status_data data Output 4

