package require -exact qsys 14.1

add_instance sld_hub_controller_system_0 altera_sld_hub_controller_system
set_instance_parameter_value sld_hub_controller_system_0 {ENABLE_JTAG_IO_SELECTION} {0}

add_connection hps_0.h2f_user1_clock sld_hub_controller_system_0.clk clock

add_connection hps_0.h2f_reset sld_hub_controller_system_0.reset reset

add_connection hps_0.h2f_lw_axi_master sld_hub_controller_system_0.s0 avalon
set_connection_parameter_value hps_0.h2f_lw_axi_master/sld_hub_controller_system_0.s0 arbitrationPriority {1}
set_connection_parameter_value hps_0.h2f_lw_axi_master/sld_hub_controller_system_0.s0 baseAddress {0x00030000}
set_connection_parameter_value hps_0.h2f_lw_axi_master/sld_hub_controller_system_0.s0 defaultConnection {0}

add_connection fpga_only_master.master sld_hub_controller_system_0.s0 avalon
set_connection_parameter_value fpga_only_master.master/sld_hub_controller_system_0.s0 arbitrationPriority {1}
set_connection_parameter_value fpga_only_master.master/sld_hub_controller_system_0.s0 baseAddress {0x00030000}
set_connection_parameter_value fpga_only_master.master/sld_hub_controller_system_0.s0 defaultConnection {0}

save_system
