# TCL File Generated by Component Editor 14.0
# Wed Oct 01 21:14:32 PDT 2014
# DO NOT MODIFY


# 
# memtest_controller "Memtest Controller" v1.0
#  2014.10.01.21:14:32
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module memtest_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME memtest_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Memtest Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property GROUP {Memtest}

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL memtest_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file memtest_controller.sv SYSTEM_VERILOG PATH memtest_controller.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL memtest_controller
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file memtest_controller.sv SYSTEM_VERILOG PATH memtest_controller.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL memtest_controller
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file memtest_controller.sv SYSTEM_VERILOG PATH memtest_controller.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point control
# 
add_interface control avalon end
set_interface_property control addressUnits WORDS
set_interface_property control associatedClock clock
set_interface_property control associatedReset reset
set_interface_property control bitsPerSymbol 8
set_interface_property control burstOnBurstBoundariesOnly false
set_interface_property control burstcountUnits WORDS
set_interface_property control explicitAddressSpan 0
set_interface_property control holdTime 0
set_interface_property control linewrapBursts false
set_interface_property control maximumPendingReadTransactions 0
set_interface_property control maximumPendingWriteTransactions 0
set_interface_property control readLatency 0
set_interface_property control readWaitStates 0
set_interface_property control readWaitTime 0
set_interface_property control setupTime 1
set_interface_property control timingUnits Cycles
set_interface_property control writeWaitTime 0
set_interface_property control ENABLED true
set_interface_property control EXPORT_OF ""
set_interface_property control PORT_NAME_MAP ""
set_interface_property control CMSIS_SVD_VARIABLES ""
set_interface_property control SVD_ADDRESS_GROUP ""

add_interface_port control avs_control_read read Input 1
add_interface_port control avs_control_write write Input 1
add_interface_port control avs_control_address address Input 4
add_interface_port control avs_control_writedata writedata Input 32
add_interface_port control avs_control_readdata readdata Output 32
set_interface_assignment control embeddedsw.configuration.isFlash 0
set_interface_assignment control embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment control embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment control embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pktstatus
# 
add_interface pktstatus avalon_streaming end
set_interface_property pktstatus associatedClock clock
set_interface_property pktstatus associatedReset reset
set_interface_property pktstatus dataBitsPerSymbol 4
set_interface_property pktstatus errorDescriptor ""
set_interface_property pktstatus firstSymbolInHighOrderBits true
set_interface_property pktstatus maxChannel 0
set_interface_property pktstatus readyLatency 0
set_interface_property pktstatus ENABLED true
set_interface_property pktstatus EXPORT_OF ""
set_interface_property pktstatus PORT_NAME_MAP ""
set_interface_property pktstatus CMSIS_SVD_VARIABLES ""
set_interface_property pktstatus SVD_ADDRESS_GROUP ""

add_interface_port pktstatus asi_pktstatus_data data Input 4


# 
# connection point cmpstatus
# 
add_interface cmpstatus avalon_streaming end
set_interface_property cmpstatus associatedClock clock
set_interface_property cmpstatus associatedReset reset
set_interface_property cmpstatus dataBitsPerSymbol 4
set_interface_property cmpstatus errorDescriptor ""
set_interface_property cmpstatus firstSymbolInHighOrderBits true
set_interface_property cmpstatus maxChannel 0
set_interface_property cmpstatus readyLatency 0
set_interface_property cmpstatus ENABLED true
set_interface_property cmpstatus EXPORT_OF ""
set_interface_property cmpstatus PORT_NAME_MAP ""
set_interface_property cmpstatus CMSIS_SVD_VARIABLES ""
set_interface_property cmpstatus SVD_ADDRESS_GROUP ""

add_interface_port cmpstatus asi_cmpstatus_data data Input 4


# 
# connection point seed
# 
add_interface seed avalon_streaming start
set_interface_property seed associatedClock clock
set_interface_property seed associatedReset reset
set_interface_property seed dataBitsPerSymbol 8
set_interface_property seed errorDescriptor ""
set_interface_property seed firstSymbolInHighOrderBits true
set_interface_property seed maxChannel 0
set_interface_property seed readyLatency 0
set_interface_property seed ENABLED true
set_interface_property seed EXPORT_OF ""
set_interface_property seed PORT_NAME_MAP ""
set_interface_property seed CMSIS_SVD_VARIABLES ""
set_interface_property seed SVD_ADDRESS_GROUP ""

add_interface_port seed aso_seed_valid valid Output 1
add_interface_port seed aso_seed_data data Output 128


# 
# connection point size
# 
add_interface size avalon_streaming start
set_interface_property size associatedClock clock
set_interface_property size associatedReset reset
set_interface_property size dataBitsPerSymbol 8
set_interface_property size errorDescriptor ""
set_interface_property size firstSymbolInHighOrderBits true
set_interface_property size maxChannel 0
set_interface_property size readyLatency 0
set_interface_property size ENABLED true
set_interface_property size EXPORT_OF ""
set_interface_property size PORT_NAME_MAP ""
set_interface_property size CMSIS_SVD_VARIABLES ""
set_interface_property size SVD_ADDRESS_GROUP ""

add_interface_port size aso_size_valid valid Output 1
add_interface_port size aso_size_data data Output 32


# 
# connection point comperr
# 
add_interface comperr avalon_streaming end
set_interface_property comperr associatedClock clock
set_interface_property comperr associatedReset reset
set_interface_property comperr dataBitsPerSymbol 8
set_interface_property comperr errorDescriptor ""
set_interface_property comperr firstSymbolInHighOrderBits true
set_interface_property comperr maxChannel 0
set_interface_property comperr readyLatency 0
set_interface_property comperr ENABLED true
set_interface_property comperr EXPORT_OF ""
set_interface_property comperr PORT_NAME_MAP ""
set_interface_property comperr CMSIS_SVD_VARIABLES ""
set_interface_property comperr SVD_ADDRESS_GROUP ""

add_interface_port comperr asi_comperr_valid valid Input 1
add_interface_port comperr asi_comperr_data data Input 128


# 
# connection point cmppktstatus
# 
add_interface cmppktstatus avalon_streaming end
set_interface_property cmppktstatus associatedClock clock
set_interface_property cmppktstatus associatedReset reset
set_interface_property cmppktstatus dataBitsPerSymbol 4
set_interface_property cmppktstatus errorDescriptor ""
set_interface_property cmppktstatus firstSymbolInHighOrderBits true
set_interface_property cmppktstatus maxChannel 0
set_interface_property cmppktstatus readyLatency 0
set_interface_property cmppktstatus ENABLED true
set_interface_property cmppktstatus EXPORT_OF ""
set_interface_property cmppktstatus PORT_NAME_MAP ""
set_interface_property cmppktstatus CMSIS_SVD_VARIABLES ""
set_interface_property cmppktstatus SVD_ADDRESS_GROUP ""

add_interface_port cmppktstatus asi_cmppktstatus_data data Input 4

