# TCL File Generated by Component Editor 14.0
# Wed Oct 01 21:07:18 PDT 2014
# DO NOT MODIFY


# 
# avst_comparator_128bits "AvST Comparator 128 Bits" v1.0
#  2014.10.01.21:07:18
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module avst_comparator_128bits
# 
set_module_property DESCRIPTION ""
set_module_property NAME avst_comparator_128bits
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "AvST Comparator 128 Bits"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property GROUP {Memtest}

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avst_compare
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avst_compare.sv SYSTEM_VERILOG PATH avst_compare.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avst_compare
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avst_compare.sv SYSTEM_VERILOG PATH avst_compare.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL avst_compare
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avst_compare.sv SYSTEM_VERILOG PATH avst_compare.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point indata
# 
add_interface indata avalon_streaming end
set_interface_property indata associatedClock clock
set_interface_property indata associatedReset reset
set_interface_property indata dataBitsPerSymbol 8
set_interface_property indata errorDescriptor ""
set_interface_property indata firstSymbolInHighOrderBits true
set_interface_property indata maxChannel 0
set_interface_property indata readyLatency 0
set_interface_property indata ENABLED true
set_interface_property indata EXPORT_OF ""
set_interface_property indata PORT_NAME_MAP ""
set_interface_property indata CMSIS_SVD_VARIABLES ""
set_interface_property indata SVD_ADDRESS_GROUP ""

add_interface_port indata asi_indata_valid valid Input 1
add_interface_port indata asi_indata_ready ready Output 1
add_interface_port indata asi_indata_data data Input 128
add_interface_port indata asi_indata_sop startofpacket Input 1
add_interface_port indata asi_indata_eop endofpacket Input 1


# 
# connection point compdata
# 
add_interface compdata avalon_streaming end
set_interface_property compdata associatedClock clock
set_interface_property compdata associatedReset reset
set_interface_property compdata dataBitsPerSymbol 8
set_interface_property compdata errorDescriptor ""
set_interface_property compdata firstSymbolInHighOrderBits true
set_interface_property compdata maxChannel 0
set_interface_property compdata readyLatency 0
set_interface_property compdata ENABLED true
set_interface_property compdata EXPORT_OF ""
set_interface_property compdata PORT_NAME_MAP ""
set_interface_property compdata CMSIS_SVD_VARIABLES ""
set_interface_property compdata SVD_ADDRESS_GROUP ""

add_interface_port compdata asi_compdata_valid valid Input 1
add_interface_port compdata asi_compdata_ready ready Output 1
add_interface_port compdata asi_compdata_data data Input 128
add_interface_port compdata asi_compdata_sop startofpacket Input 1
add_interface_port compdata asi_compdata_eop endofpacket Input 1


# 
# connection point err
# 
add_interface err avalon_streaming start
set_interface_property err associatedClock clock
set_interface_property err associatedReset reset
set_interface_property err dataBitsPerSymbol 8
set_interface_property err errorDescriptor ""
set_interface_property err firstSymbolInHighOrderBits true
set_interface_property err maxChannel 0
set_interface_property err readyLatency 0
set_interface_property err ENABLED true
set_interface_property err EXPORT_OF ""
set_interface_property err PORT_NAME_MAP ""
set_interface_property err CMSIS_SVD_VARIABLES ""
set_interface_property err SVD_ADDRESS_GROUP ""

add_interface_port err aso_err_valid valid Output 1
add_interface_port err aso_err_data data Output 128


# 
# connection point status
# 
add_interface status avalon_streaming start
set_interface_property status associatedClock clock
set_interface_property status associatedReset reset
set_interface_property status dataBitsPerSymbol 4
set_interface_property status errorDescriptor ""
set_interface_property status firstSymbolInHighOrderBits true
set_interface_property status maxChannel 0
set_interface_property status readyLatency 0
set_interface_property status ENABLED true
set_interface_property status EXPORT_OF ""
set_interface_property status PORT_NAME_MAP ""
set_interface_property status CMSIS_SVD_VARIABLES ""
set_interface_property status SVD_ADDRESS_GROUP ""

add_interface_port status aso_status_data data Output 4

